In [79]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/weather/weather_classification_data.csv
/kaggle/input/weather-type-classification/weather_classification_data.csv


In [80]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [81]:
dataset = pd.read_csv('/kaggle/input/weather-type-classification/weather_classification_data.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [82]:
print(X)

[[14.0 73 9.5 ... 'Winter' 3.5 'inland']
 [39.0 96 8.5 ... 'Spring' 10.0 'inland']
 [30.0 64 7.0 ... 'Spring' 5.5 'mountain']
 ...
 [30.0 77 5.5 ... 'Autumn' 9.0 'coastal']
 [3.0 76 10.0 ... 'Winter' 2.0 'inland']
 [-5.0 38 0.0 ... 'Autumn' 10.0 'mountain']]


In [83]:
'''from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')
X = np.array(ct.fit_transform(X))'''

"from sklearn.compose import ColumnTransformer\nfrom sklearn.preprocessing import OneHotEncoder\n\nct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [4])], remainder='passthrough')\nX = np.array(ct.fit_transform(X))"

In [84]:
print(X)

[[14.0 73 9.5 ... 'Winter' 3.5 'inland']
 [39.0 96 8.5 ... 'Spring' 10.0 'inland']
 [30.0 64 7.0 ... 'Spring' 5.5 'mountain']
 ...
 [30.0 77 5.5 ... 'Autumn' 9.0 'coastal']
 [3.0 76 10.0 ... 'Winter' 2.0 'inland']
 [-5.0 38 0.0 ... 'Autumn' 10.0 'mountain']]


In [85]:
print(y)

['Rainy' 'Cloudy' 'Sunny' ... 'Cloudy' 'Snowy' 'Rainy']


In [86]:
dataset.isnull().sum()

Temperature             0
Humidity                0
Wind Speed              0
Precipitation (%)       0
Cloud Cover             0
Atmospheric Pressure    0
UV Index                0
Season                  0
Visibility (km)         0
Location                0
Weather Type            0
dtype: int64

In [87]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, -1] = le.fit_transform(X[:, -1])
X[:, 4] = le.fit_transform(X[:, 4])
X[:, -3] = le.fit_transform(X[:, -3])

In [88]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
toenc=["Cloud Cover","Season","Location","Weather Type"]
for i in toenc:
    dataset[i]=le.fit_transform(dataset[i])

In [89]:
print(X)

[[14.0 73 9.5 ... 3 3.5 1]
 [39.0 96 8.5 ... 1 10.0 1]
 [30.0 64 7.0 ... 1 5.5 2]
 ...
 [30.0 77 5.5 ... 0 9.0 0]
 [3.0 76 10.0 ... 3 2.0 1]
 [-5.0 38 0.0 ... 0 10.0 2]]


In [90]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [91]:
x=dataset.drop('Weather Type',axis=1)
y=dataset['Weather Type']

In [92]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [93]:
ann = tf.keras.models.Sequential()

In [94]:
ann.add(tf.keras.layers.Dense(units=60, activation='relu'))

In [95]:
ann.add(tf.keras.layers.Dense(units=30, activation='relu'))

In [96]:
ann.add(tf.keras.layers.Dense(units=4, activation='softmax'))

In [99]:
ann.compile(optimizer=keras.optimizers.Adam(learning_rate=0.001),
               loss='sparse_categorical_crossentropy',
               metrics=['accuracy'])

In [ ]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

In [ ]:
loss,accu=ann.evaluate(X_test,y_test)
print(loss,accu)

In [ ]:
tc=(39.0,96,8.5,71.0,'partly cloudy',1011.43,7,'Spring',10.0,'inland')
tc=le.fit_transform(tc)
tc=np.array(tc).reshape(1,-1)
ans=model.predict(tc)
print(ans)
ans=np.argmax(ans)
print(ans)